kube-prometheus-stack:
  grafana:
    enabled: true
    admin:
      existingSecret: grafana-admin
      secretKey: password
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: selfsigned
      hosts:
        - grafana.homelab.local
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.homelab.local
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

  prometheus:
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: selfsigned
      hosts:
        - prometheus.homelab.local
      tls:
        - secretName: prometheus-tls
          hosts:
            - prometheus.homelab.local
    prometheusSpec:
      retention: 5d
      retentionSize: 2GB
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi

  alertmanager:
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: selfsigned
      hosts:
        - alertmanager.homelab.local
      tls:
        - secretName: alertmanager-tls
          hosts:
            - alertmanager.homelab.local
    alertmanagerSpec:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi

  kube-state-metrics:
    resources:
      requests:
        cpu: 20m
        memory: 64Mi
      limits:
        cpu: 150m
        memory: 128Mi

  prometheus-node-exporter:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 64Mi

  defaultRules:
    rules:
      etcd: false
      kubeScheduler: false
      kubeControllerManager: false
