apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  namespace: metallb-system # new namespace
  name: home-pool
spec:
  addresses:
  - 192.168.1.210-192.168.1.220 # Fixed IP

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  namespace: metallb-system
  name: home-adv
