apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  namespace: metallb
  name: home-pool
spec:
  addresses:
  - 192.168.178.210-192.168.178.220

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  namespace: metallb
  name: home-adv