cert-manager:
  installCRDs: true
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

clusterIssuers:
  enabled: true
  email: diogofrmota@gmail.com