cert-manager:
  installCRDs: true
  prometheus:
    enabled: true
    servicemonitor:
      enabled: true
  config:
    featureGates:
      # Disable the use of Exact PathType in Ingress resources, to work around a bug in ingress-nginx
      # https://github.com/kubernetes/ingress-nginx/issues/11176
      ACMEHTTP01IngressPathTypeExact: false
  
  webhook:
    service:
      port: 443
      targetPort: 10250
          
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

clusterIssuers:
  enabled: true
  email: diogofrmota@gmail.com
