apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: argocd
          - name: cert-manager
          - name: ingress-nginx
          - name: metallb
          
  template:
    metadata:
      name: "{{ .name }}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: "."
    spec:
      project: default
      source:
        repoURL: https://github.com/diogofrmota/homelab.git
        targetRevision: HEAD
        path: "k8s-apps/{{ .name }}"
      destination:
        name: in-cluster
        namespace: '{{ default .name (dig "namespace" "" .) }}'
      ignoreDifferences:
        - group: apps
          kind: "*"
          jqPathExpressions:
            - .spec.template.spec.hostUsers
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true