{{- if .Values.server.ingress.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}-server
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: argocd
spec:
  secretName: argocd-server-tls
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  dnsNames:
    - argocd.homelab.local
{{- end }}