apiVersion: v2
name: homepage
description: A highly customizable homepage (or startpage / application dashboard) with Docker and service API integrations
type: application
version: 0.1.0
dependencies:
  - name: app-template
    version: 2.6.0
    repository: https://bjw-s-labs.github.io/helm-charts