homepage:
  image:
    repository: ghcr.io/gethomepage/homepage
    tag: v1.5.0@sha256:e7fc26f914cf5e7dcd6c566e24ca218addb879aa76478ad4a553b1f9ae48b1d7

  env:
    - name: HOMEPAGE_ALLOWED_HOSTS
      value: "apps.diogomota.pt"

  enableRbac: true

  serviceAccount:
    name: ""
    create: true

  service:
    main:
      ports:
        http:
          port: 3000

  controller:
    strategy: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

  ingress:
    main:
      enabled: true
      annotations:
        gethomepage.dev/enabled: "false"
        gethomepage.dev/name: "Homepage"
        gethomepage.dev/description: "A modern, secure, highly customizable application dashboard."
        gethomepage.dev/group: "A New Group"
        gethomepage.dev/icon: "homepage"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/whitelist-source-range: "0.0.0.0/0"
      ingressClassName: "nginx"
      hosts:
        - host: &host "apps.diogomota.pt"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: homepage-tls
          hosts:
            - *host

  config:
    settings:
      title: Homepage - Diogo's Homelab
      background: https://i.redd.it/8tlwnse4q0f11.jpg
      backgroundOpacity: 0.7
      cardBlur: md
      theme: dark
      headerStyle: boxed
      hideVersion: true
      layout:
        Infrastructure:
          style: row
          columns: 3
        Monitoring:
          style: row
          columns: 3
        Other Apps:
          style: column
        bookmarks:
          style: row
          columns: 2

    widgets:
      - resources:
          backend: resources
          expanded: true
          cpu: true
          memory: true

      - kubernetes:
          cluster:
            show: true
            cpu: true
            memory: true
            showLabel: true
            label: "cluster"
          nodes:
            show: true
            cpu: true
            memory: true
            showLabel: true

      - datetime:
          text_size: xl
          format:
            timeStyle: medium

      - openmeteo:
          latitude: 38.7223
          longitude: 9.1393
          units: metric
          cache: 5
    kubernetes:
      mode: cluster
    docker:

    services:
      - Infrastructure:
          - Cert-Manager (TLS certificates management):
              description: Automating Let's Encrypt TLS certificate management in Kubernetes, handling the issuance and renewal.
              icon: https://gitlab.com/uploads/-/system/project/avatar/17168204/cert-manager-oci.png
          - Ingress-nginx (Ingress controller):
              description: Ingress controller for Kubernetes using NGINX as a reverse proxy and load balancer, managing traffic routing, SSL/TLS termination, and exposing services.
              icon: https://cdn.iconscout.com/icon/free/png-256/free-nginx-logo-icon-svg-download-png-3030173.png
          - Metallb (Load balancer):
              description: Load balancer that assigns IP addresses from the local network to Kubernetes services, making them accessible from outside the cluster.
              icon: https://artifacthub.io/image/51e10aa9-e31b-47c7-817b-12f9f3b5c05a@3x
      - Monitoring:
          - Grafana (Monitoring Dashboard):
              href: https://grafana.diogomota.pt/
              description: Platform for analytics and monitoring, visualizing time-series data from sources like Prometheus.
              icon: https://assets.streamlinehq.com/image/private/w_300,h_300,ar_1/f_auto/v1/icons/3/grafana-ipeuuhi0ws3fbikv7ojrk.png/grafana-625ktq51icaz2carazn0n.png
          - Prometheus (Metrics collection):
              description: Systems monitoring and alerting toolkit that collects and stores time-series metrics from configured targets.
              icon: https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Prometheus_software_logo.svg/775px-Prometheus_software_logo.svg.png
          - Alertmanager (Alerting):
              description: Handles alerts from Prometheus by deduplicating, grouping, and routing them to the correct receiver such as email and Telegram.
              icon: https://prometheus.io/twitter-image.png?b370f6418ef38b42

      - Other Apps:
          - ArgoCD (GitOps):
              href: https://argocd.diogomota.pt/
              description: Declarative, GitOps continuous delivery tool for managing homelab's Kubernetes infrastructure.
              icon: https://miro.medium.com/v2/resize:fit:1358/format:webp/1*zVLT-SMHrZKqwqfNPm4fkQ.png
 
    bookmarks:
      - Inside the cluster:
          - Homepage - Custom dashboard for the homelab, with service API integrations:
              - href: https://apps.diogomota.pt/
                icon: https://cdn-icons-png.flaticon.com/512/5097/5097332.png
                #abbr: Home
          - Personal Website - Web Page showcasing professional experience and main projects:
              - href: https://diogomota.pt/
                icon: https://cdn-icons-png.flaticon.com/512/909/909212.png
                #abbr: PW
      - Outside the cluster:
          - GitHub - Homelab Documentation and Git Repository:
              - href: https://github.com/diogofrmota/homelab
                icon: https://github.com/fluidicon.png
                #abbr: GH
          - Gitlab - Manage Secrets (access tokens/ credentials):
              - href: https://gitlab.com/diogofrmota-group/homelab/
                icon: https://gitlab.com/assets/favicon-72a2cad5025aa931d6ea56c3201d1f18e68a8cd39788c7c80d5b2b82aa5143ef.png
                #abbr: GL

  persistence:
    logs:
      enabled: true
      type: emptyDir
      mountPath: /app/config/logs