homepage:
  image:
    repository: ghcr.io/gethomepage/homepage
    tag: v1.5.0@sha256:e7fc26f914cf5e7dcd6c566e24ca218addb879aa76478ad4a553b1f9ae48b1d7

  env:
    - name: HOMEPAGE_ALLOWED_HOSTS
      value: "apps.diogomota.pt"

  enableRbac: true

  serviceAccount:
    name: ""
    create: true

  service:
    main:
      ports:
        http:
          port: 3000

  controller:
    strategy: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

  ingress:
    main:
      enabled: true
      annotations:
        gethomepage.dev/enabled: "false"
        gethomepage.dev/name: "Homepage"
        gethomepage.dev/description: "A modern, secure, highly customizable application dashboard."
        gethomepage.dev/group: "A New Group"
        gethomepage.dev/icon: "homepage"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/whitelist-source-range: "0.0.0.0/0"
      ingressClassName: "nginx"
      hosts:
        - host: &host "apps.diogomota.pt"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: homepage-tls
          hosts:
            - *host

  config:
    settings:
      background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
      cardBlur: md
      theme: dark
      headerStyle: boxed
      hideVersion: true
      layout:
        Media:
          style: row
          columns: 4

    widgets:
      - resources:
          backend: resources
          expanded: true
          cpu: true
          memory: true

      - kubernetes:
          cluster:
            show: true
            cpu: true
            memory: true
            showLabel: true
            label: "cluster"
          nodes:
            show: true
            cpu: true
            memory: true
            showLabel: true

      - datetime:
          text_size: xl
          format:
            timeStyle: medium

      - openmeteo:
          latitude: 38.7223
          longitude: 9.1393
          units: Metric
          cache: 5
    kubernetes:
      mode: cluster
    docker:

    services:
      - GitOps & Monitoring:
          - ArgoCD:
              href: https://argocd.diogomota.pt/
              description: Declarative, GitOps continuous delivery tool for managing homelab's Kubernetes infrastructure.
              icon: https://argo-cd.readthedocs.io/en/stable/assets/favicon.png
          - Grafana:
              href: https://grafana.diogomota.pt/
              description: Interactive dashboards for real-time monitoring and data analytics.
              icon: https://grafana.com/favicon.ico   
      - Static Pages:
          - Homepage:
              href: https://apps.diogomota.pt/
              description: Centralized, custom dashboard for the homelab, with service API integrations.
              icon: https://cdn-icons-png.flaticon.com/512/5097/5097332.png
          - Portfolio:
              href: https://diogomota.pt/
              description: Web Page showcasing professional experience and main projects.
              icon: https://wallpapers.com/images/hd/document-icon-graphic-ry6hxlmiuy2qzh2g-2.jpg
 
    bookmarks:
      - Bookmarked Webpages:
          - GitHub - Host of homelab full documentation, scripts and source files:
              - abbr: GH
                href: https://github.com/diogofrmota/homelab
                icon: https://github.com/fluidicon.png
          - Gitlab - DevOps platform for code repository, CI/CD and secure secrets (access tokens/ credentials):
              - abbr: GL
                href: https://gitlab.com/diogofrmota-group/homelab/
                icon: https://gitlab.com/assets/favicon-72a2cad5025aa931d6ea56c3201d1f18e68a8cd39788c7c80d5b2b82aa5143ef.png

  persistence:
    logs:
      enabled: true
      type: emptyDir
      mountPath: /app/config/logs