ingress-nginx:
  controller:
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.210
    config:
      ssl-protocols: TLSv1.2 TLSv1.3
      ssl-ciphers: ECDHE-RSA-AES128-GCM-SHA256,ECDHE-RSA-AES256-GCM-SHA384
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
