ingress-nginx:
  controller:
    replicaCount: 1
    service:
      type: LoadBalancer
      loadBalancerIP: "192.168.1.210"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

    allowSnippetAnnotations: "true"

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

    topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: '{{ include "ingress-nginx.name" . }}'
            app.kubernetes.io/instance: "{{ .Release.Name }}"
            app.kubernetes.io/component: controller
        matchLabelKeys:
          - pod-template-hash
        topologyKey: kubernetes.io/hostname
        maxSkew: 1
        whenUnsatisfiable: ScheduleAnyway
  ingress:
    options:
      allow-snippet-annotations: "true"