ingress-nginx:
  controller:
    replicaCount: 1
    service:
      type: LoadBalancer
      loadBalancerIP: "192.168.1.210"

    allowSnippetAnnotations: "true"

    topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: '{{ include "ingress-nginx.name" . }}'
            app.kubernetes.io/instance: "{{ .Release.Name }}"
            app.kubernetes.io/component: controller
        matchLabelKeys:
          - pod-template-hash
        topologyKey: kubernetes.io/hostname
        maxSkew: 1
        whenUnsatisfiable: ScheduleAnyway
  ingress:
    options:
      allow-snippet-annotations: "true"