external-dns:
  provider: cloudflare

  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-secrets
          key: api-token
    - name: CF_API_EMAIL
      valueFrom:
        secretKeyRef:
          name: cloudflare-secrets
          key: email

  sources:
    - ingress
    - service

  domainFilters:
    - diogomota.pt

  txtOwnerId: k8s-cluster

  policy: sync

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi