oauth2-proxy:
  proxyVarsAsSecrets: true
  config:
    # existingSecret: google-oauth2-credentials
    # Configuring email_domains as an empty array acts as a deny all
    configFile: |-
      email_domains = ["*"]

  # extraArgs:
  # For ingress-nginx
  # set-xauthrequest: true

  # Gitlab
  # provider: gitlab
  # oidc-issuer-url: https://gitlab.com

  # Google
  # provider: google

  # authenticatedEmailsFile:
  #   enabled: false
  #   # Restrict access to specific email addresses
  #   restricted_access: |-
  #     istarkillerpt@gmail.com

  alphaConfig:
    enabled: true
    configData:
      providers:
        # - id: google
        #   name: Google
        #   clientId: 602698434371-n8g8cpp5faibnn7ldet4q09j176umpnb.apps.googleusercontent.com
        #   clientSecretFile: /mnt/google/clientSecret
        #   provider: google
        #   code_challenge_method: S256
        #   scope: "openid email"
        #   oidcConfig:
        #     issuerURL: https://accounts.google.com

        - id: gitlab
          name: Gitlab
          clientId: e755bb3469cf446877b7489dc3c863766ab4d37b389ecc21a94e2334cecd927c
          clientSecretFile: /mnt/gitlab/clientSecret
          provider: gitlab
          code_challenge_method: S256
          scope: "openid email"
          gitlabConfig:
            group:
              - diogofrmota-group
          oidcConfig:
            issuerURL: https://gitlab.com
            audienceClaims: ["aud"]
      injectResponseHeaders:
        - name: X-Auth-Request-Email
          values:
            - claim: email
        - name: X-Auth-Request-User
          values:
            - claim: preferred_username

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      external-dns.alpha.kubernetes.io/target: home.diogomota.pt
      nginx.ingress.kubernetes.io/whitelist-source-range: "0.0.0.0/0"
    className: nginx
    path: /oauth2
    pathType: Prefix
    # Every host that needs oauth authentication
    hosts:
      - alertmanager.diogomota.pt
      - argocd.diogomota.pt
      - cd.diogomota.pt
      - grafana.diogomota.pt
      - headscale.diogomota.pt
      - pihole.diogomota.pt
      - prometheus.diogomota.pt
      - tailout.diogomota.pt

  metrics:
    enabled: true
    servicemonitor:
      enabled: true

  extraVolumes:
    - name: gitlab-oauth-secret
      secret:
        secretName: gitlab-oauth2-credentials
        items:
          - key: client-secret
            path: clientSecret
          - key: cookie-secret
            path: cookieSecret

  extraVolumeMounts:
    - name: gitlab-oauth-secret
      mountPath: /mnt/gitlab
