pihole:
  replicaCount: 1
  strategyType: RollingUpdate
  maxSurge: 1
  maxUnavailable: 1

  image:
    repository: "pihole/pihole"
    tag: "2025.08.0@sha256:90a1412b3d3037d1c22131402bde19180d898255b584d685c84d943cf9c14821"
    pullPolicy: IfNotPresent

  serviceTcp:
    loadBalancerIP: 192.168.1.214
    type: LoadBalancer
    annotations: {}

  serviceUdp:
    loadBalancerIP: 192.168.1.213
    type: LoadBalancer
    annotations: {}

  persistence:
    enabled: true
    size: 2Gi
    
  env:
    TZ: "Europe/Lisbon"
    WEBPASSWORD:
      valueFrom:
        secretKeyRef:
          name: pihole-password
          key: password
    DNS1: "8.8.8.8"
    DNS2: "8.8.4.4"

  ingress:
    enabled: false

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi