apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/diogofrmota/homelab
    path: applications/
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true