argo-cd:
  server:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: selfsigned
        cert-manager.io/issue-temporary-certificate: "true"
        external-dns.alpha.kubernetes.io/target: home.homelab.local
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      ingressClassName: nginx
      pathType: ImplementationSpecific
      hostname:
        argocd.homelab.local
      tls: true
      ingressClassName: nginx
      https: true