argo-cd:
  server:
    service:
      type: ClusterIP
    serviceLabels:
      app.kubernetes.io/name: argocd-server
      app.kubernetes.io/component: server
      app.kubernetes.io/part-of: argocd
    selector:
      app.kubernetes.io/name: argocd-server
    extraArgs:
      - --insecure
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: selfsigned
      hosts:
        - argocd.homelab.local
      tls:
        - secretName: argocd-tls
          hosts:
            - argocd.homelab.local
  
  configs:
    secret:
      create: false

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi