argo-cd:
  # repoServer resources
  repoServer:
    serviceLabels:
      app.kubernetes.io/instance: argocd  
      app.kubernetes.io/name: argocd-repo-server
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  controller:
    serviceLabels:
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/name: argocd-application-controller
  dexServer:
    serviceLabels:
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/name: argocd-dex-server
  notificationsController:
    serviceLabels:
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/name: argocd-notifications-controller
  redis:
    serviceLabels:
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/name: argocd-redis
  server:
    service:
      type: ClusterIP
    serviceLabels:
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/name: argocd-server
    extraArgs:
      - --insecure
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: selfsigned
      hosts:
        - argocd.homelab.local
      tls:
        - secretName: argocd-tls
          hosts:
            - argocd.homelab.local
  
  configs:
    secret:
      create: false

  # for controller/server
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

