argo-cd:
  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts: 
        - argocd.homelab.local
      paths: 
        - /
      annotations:
        cert-manager.io/cluster-issuer: selfsigned
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      tls:
        - secretName: argocd-server-tls
          hosts:
            - argocd.homelab.local
  config:
    url: https://argocd.homelab.local
  
  global:
    image:
      tag: "v3.1.8"