argo-cd:
  #REMOVED TEMPORARILY - ADD WHEN KUBE-PROMETHEUS-STACK IS ADDED
  #controller:
  #  metrics:
  #    enabled: true
  #    serviceMonitor:
  #      enabled: true
  #    rules:
  #      enabled: true
  #      spec:
  #        - alert: ArgoCDApplicationNotSynced
  #          expr: argocd_app_info{sync_status!="Synced"} != 0
  #          for: 15m
  #          labels:
  #            severity: warning
  #          annotations:
  #            summary: ArgoCD application not synced (instance {{ $labels.instance }})
  #            description: "Application {{ $labels.name }} run by argo is currently not in sync - Value = {{ $value }}"
  #        - alert: ArgoCDApplicationUnhealthy
  #          expr: argocd_app_info{health_status!~"Healthy|Suspended"} != 0
  #          for: 15m
  #          labels:
  #            severity: warning
  #          annotations:
  #            summary: ArgoCD application unhealthy (instance {{ $labels.instance }})
  #            description: "Application {{ $labels.name }} run by argo is currently not healthy - Value = {{ $value }}"
  
  resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

  #REMOVED TEMPORARILY - ADD WHEN KUBE-PROMETHEUS-STACK IS ADDED
  #dex:
  #  metrics:
  #    enabled: true
  #    serviceMonitor:
  #      enabled: true

  #REMOVED TEMPORARILY - ADD WHEN KUBE-PROMETHEUS-STACK IS ADDED
  #redis:
  #  metrics:
  #    enabled: true
  #    serviceMonitor:
  #      enabled: true

  repoServer:
    useEphemeralHelmWorkingDir: false
    logLevel: warn
    #REMOVED TEMPORARILY - ADD WHEN KUBE-PROMETHEUS-STACK IS ADDED
    #metrics:
    #  enabled: true
    #  serviceMonitor:
    #    enabled: true
    env:
      - name: HELM_PLUGINS
        value: /home/argocd/cmp-server/plugins

    initContainers:
      - name: helm-plugin-install
        image: alpine/helm:3@sha256:9b9dab5f1185f02264fde67306137e658017f9d686385acaec7fbadbf156a6aa
        command: ["/bin/sh", "-c"]
        args:
          - |
            helm plugin install https://github.com/aslafy-z/helm-git;
            helm plugin install https://github.com/hypnoglow/helm-s3;
        env:
          - name: HELM_PLUGINS
            value: /home/argocd/cmp-server/plugins
        volumeMounts:
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins

  #REMOVED TEMPORARILY - ADD WHEN KUBE-PROMETHEUS-STACK IS ADDED
  #applicationSet:
  #  metrics:
  #    enabled: true
  #    serviceMonitor:
  #      enabled: true

  notifications:
    enabled: true
    secret:
      create: false
      name: argocd-notifications-controller-secret
    argocdUrl: https://argocd.homelab.local
    extraEnv:
      - name: TZ
        value: Europe/Lisbon
    
    #REMOVED TEMPORARILY - ADD WHEN KUBE-PROMETHEUS-STACK IS ADDED
    #metrics:
    #  enabled: false
    #  serviceMonitor:
    #    enabled: false

  #REMOVED TEMPORARILY - ADD WHEN KUBE-PROMETHEUS-STACK IS ADDED
  #server:
  #  metrics:
  #    enabled: false
  #    serviceMonitor:
  #      enabled: false

  service:
    type: ClusterIP
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: selfsigned
      cert-manager.io/issue-temporary-certificate: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    pathType: ImplementationSpecific
    hostname:
      argocd.homelab.local
    tls: true
    ingressClassName: nginx
    https: true