argo-cd:
  server:
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - argocd.diogomota.pt
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      tls:
        - secretName: argocd-tls
          hosts:
            - argocd.diogomota.pt
  configs:
    params:
      server.insecure: false