apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: home-pool
  namespace: metallb
spec:
  addresses:
  {{- range .Values.ipAddressPool.addresses }}
  - {{ . }}
  {{- end }}
  autoAssign: true