app-template:
  defaultPodOptions:
    automountServiceAccountToken: false
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"

  controllers:
    main:
      type: deployment
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        main:
          image:
            repository: _image_
            tag: _tag_
          env:
            TZ: Europe/Lisbon
          ports:
            - name: http
              containerPort: _port_
          probes:
            liveness:
              enabled: true
              type: HTTP
            readiness:
              enabled: true
              type: HTTP

  service:
    main:
      controller: main
      type: ClusterIP
      ports:
        http:
          port: _port_

  ingress:
    main:
      annotations:
        cert-manager.io/cluster-issuer: selfsigned
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: _app_
        gethomepage.dev/description: _description_
        gethomepage.dev/group: _group_
        gethomepage.dev/icon: _icon_
      className: "nginx"
      hosts:
        - host: &host _subdomain_.homelab.local
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - secretName: _subdomain_-tls
          hosts:
            - *host